import type { AuthLocale, AuthUiLocale } from './auth-contracts';

export const authCopy = {
  en: {
    common: {
      secure: 'Secure unified account',
      backHome: 'Back to website',
      required: 'Required',
      optional: 'Optional',
      continue: 'Continue',
      back: 'Back',
      loading: 'Please wait…',
      demo: 'Interactive demo mode: use any 6-digit code. This notice disappears when the live API is enabled.',
      privacy: 'Your business IDs are never used as login credentials.',
      apiError: 'We could not complete that request. Please try again.',
      timeoutError: 'The request took too long. Please try again.',
      networkError: 'Check your connection and try again.',
      invalidOtp: 'Enter the valid 6-digit code sent to you.',
      expiredOtp: 'This code has expired. Request a new one.',
      rateLimited: 'Too many attempts. Please wait before trying again.',
    },
    shell: {
      eyebrow: 'One account. Every learning journey.',
      title: 'A secure home for your family’s learning.',
      description: 'Access every authorized student, trial lesson, class and future service through one verified identity.',
      points: [
        'One account for all authorized students',
        'Separate secure access for every guardian',
        'Verified email, WhatsApp or mobile sign-in',
      ],
      family: 'Your family account',
      guardianA: 'Guardian 1',
      guardianB: 'Guardian 2',
      students: 'Authorized students',
    },
    login: {
      metadataTitle: 'Parent & Student Login',
      title: 'Welcome back',
      description: 'Sign in with a verified email, WhatsApp number or mobile number. No password is required.',
      identifierLabel: 'Email, WhatsApp or mobile number',
      identifierPlaceholder: 'name@example.com or +1 647 000 0000',
      identifierHint: 'Do not enter a Parent MID or Student MID.',
      requestCode: 'Send secure code',
      createAccount: 'New to Success Path Mentors?',
      createAccountLink: 'Create your family account',
      staffPrompt: 'Tutor or staff member?',
      staffLink: 'Use staff sign-in',
      codeTitle: 'Check your messages',
      codeDescription: 'Enter the 6-digit code sent to',
      codeLabel: 'Verification code',
      codePlaceholder: '000000',
      verify: 'Verify and sign in',
      resend: 'Send a new code',
      resendIn: 'Resend in {seconds}s',
      useDifferent: 'Use a different email or number',
      recovery: 'No longer have access to your verified contacts?',
      recoveryLink: 'Request account recovery',
      successTitle: 'You are securely signed in',
      successDescription: 'Your session is ready. Access is limited to your authorized family and student records.',
      enterPortal: 'Continue to your account',
    },
    register: {
      metadataTitle: 'Create an Account',
      title: 'Create your family account',
      description: 'Tell us about the guardian, student and learning request. We will create the profile and place the free trial in the assignment queue.',
      existing: 'Already registered?',
      existingLink: 'Sign in instead',
      steps: ['Guardian', 'Student', 'Learning needs', 'Review'],
      stepLabel: 'Step {current} of {total}',
      guardianTitle: 'Guardian information',
      guardianDescription: 'Use contacts you can verify. Each guardian should have an individual secure identity.',
      parentName: 'Parent or guardian full name',
      relationship: 'Relationship to student',
      relationshipOptions: ['Parent', 'Guardian', 'Other authorized adult'],
      email: 'Email address',
      whatsapp: 'WhatsApp number',
      telephone: 'Other mobile number',
      contactHint: 'Include the country code, for example +1 647 000 0000.',
      studentTitle: 'Student information',
      studentDescription: 'A new student record will be linked only after guardian verification.',
      studentName: 'Student first name',
      grade: 'Grade',
      gradePlaceholder: 'Select grade',
      learningTitle: 'Learning and trial preferences',
      learningDescription: 'Preferences help our team assign the right teacher. They do not automatically book a slot.',
      subject: 'Subject',
      curriculum: 'Curriculum',
      language: 'Preferred teaching language',
      country: 'Country',
      timezone: 'Time zone',
      preferredDay: 'Preferred day',
      preferredTime: 'Preferred time',
      select: 'Select an option',
      reviewTitle: 'Review your registration',
      reviewDescription: 'Confirm the details before creating the account and pending free-trial request.',
      consent: 'I agree to the Privacy Policy and authorize Success Path Mentors to use these details to create the account, contact me and arrange the trial.',
      submit: 'Create account & request free trial',
      noAutoBooking: 'The trial remains WAITING_FOR_ASSIGNMENT until an authorized team member confirms the teacher and time.',
      verifyTitle: 'Verify your contact',
      verifyDescription: 'Enter the 6-digit code sent to',
      existingMatchTitle: 'Existing family account found',
      existingMatchDescription: 'Verify ownership before we add this student. This prevents duplicate parent accounts.',
      reviewStatusTitle: 'Registration received for secure review',
      reviewStatusDescription: 'We found conflicting possible matches, so no account link was guessed. Our team will review the identity safely.',
      successTitle: 'Registration received',
      successDescription: 'Your account and student profile are ready. The free trial is waiting for teacher and time assignment.',
      successNext: 'Our team will confirm the free-trial teacher and time by your verified contact method.',
      registrationId: 'Registration reference',
      returnHome: 'Return to website',
      errors: {
        required: 'This field is required.',
        email: 'Enter a valid email address.',
        phone: 'Enter a valid international number with country code.',
        consent: 'Consent is required to create the account.',
      },
    },
    social: {
      continueWithGoogle: 'Continue with Google',
      continueWithFacebook: 'Continue with Facebook',
      or: 'OR',
      connecting: 'Connecting…',
      unavailableError: 'This sign-in method is currently unavailable. Try again or use email or phone below.',
      signupWithEmail: 'Sign up with Email',
      signupWithWhatsapp: 'Sign up with WhatsApp',
      signupSubtitle: 'Choose a sign-up method. Verify your identity first, then complete your account details.',
      alreadyHaveAccount: 'Already have an account?',
      signIn: 'Sign in',
      changeMethod: 'Change sign-up method',
      adultNoticeTitle: 'Notice for Families & Adult Learners',
      adultNoticeDescription: 'Online account registration is designed for family and student profiles. Adult independent learners can coordinate their personalized program directly with our team.',
      adultNoticeAction: 'Book a free trial / request',
      emailInputTitle: 'Sign up with Email',
      emailInputDescription: 'Enter your email address. We will send a secure verification code before collecting your profile details.',
      whatsappInputTitle: 'Sign up with WhatsApp',
      whatsappInputDescription: 'Enter your WhatsApp mobile number. We will send a secure verification code before collecting your profile details.',
      sendVerificationCode: 'Send verification code',
      otpTitle: 'Enter verification code',
      otpDescription: 'Enter the 6-digit code sent to',
      verifyAndContinue: 'Verify & continue',
      verifiedLabel: 'Verified Identity',
      verifiedWithGoogle: 'Verified with Google',
      verifiedWithFacebook: 'Verified with Facebook',
      verifiedWithEmail: 'Verified with Email',
      verifiedWithWhatsapp: 'Verified with WhatsApp',
    },
  },
  ar: {
    common: {
      secure: 'حساب موحّد وآمن',
      backHome: 'العودة إلى الموقع',
      required: 'مطلوب',
      optional: 'اختياري',
      continue: 'متابعة',
      back: 'رجوع',
      loading: 'يرجى الانتظار…',
      demo: 'وضع العرض التفاعلي: أدخل أي رمز مكوّن من 6 أرقام. تختفي هذه الملاحظة عند تفعيل الـAPI الفعلي.',
      privacy: 'لا تُستخدم أرقام Parent MID أو Student MID لتسجيل الدخول أبداً.',
      apiError: 'تعذر إكمال الطلب. يرجى المحاولة مرة أخرى.',
      timeoutError: 'استغرق الطلب وقتاً طويلاً. يرجى المحاولة مرة أخرى.',
      networkError: 'تحقق من اتصال الإنترنت ثم حاول مرة أخرى.',
      invalidOtp: 'أدخل رمز التحقق الصحيح المكوّن من 6 أرقام.',
      expiredOtp: 'انتهت صلاحية الرمز. اطلب رمزاً جديداً.',
      rateLimited: 'تم تجاوز عدد المحاولات. يرجى الانتظار قبل المحاولة مجدداً.',
    },
    shell: {
      eyebrow: 'حساب واحد لكل رحلة تعليمية',
      title: 'مساحة آمنة لتعلّم جميع أفراد الأسرة.',
      description: 'ادخل إلى ملفات الطلاب المصرّح لك بها والحصص والتجربة المجانية والخدمات المستقبلية من خلال هوية واحدة موثّقة.',
      points: [
        'حساب واحد لجميع الطلاب المصرّح بهم',
        'دخول مستقل وآمن لكل ولي أمر',
        'التحقق عبر البريد أو WhatsApp أو الهاتف',
      ],
      family: 'حساب الأسرة',
      guardianA: 'ولي الأمر الأول',
      guardianB: 'ولي الأمر الثاني',
      students: 'الطلاب المصرّح بهم',
    },
    login: {
      metadataTitle: 'دخول ولي الأمر والطالب',
      title: 'مرحباً بعودتك',
      description: 'سجّل الدخول باستخدام بريد إلكتروني أو رقم WhatsApp أو هاتف موثّق. لا تحتاج إلى كلمة مرور.',
      identifierLabel: 'البريد أو رقم WhatsApp أو الهاتف',
      identifierPlaceholder: 'name@example.com أو +1 647 000 0000',
      identifierHint: 'لا تدخل Parent MID أو Student MID.',
      requestCode: 'إرسال رمز آمن',
      createAccount: 'جديد لدى Success Path Mentors؟',
      createAccountLink: 'أنشئ حساب الأسرة',
      staffPrompt: 'هل أنت معلماً أو من فريق العمل؟',
      staffLink: 'استخدم دخول الموظفين',
      codeTitle: 'تحقق من رسائلك',
      codeDescription: 'أدخل الرمز المكوّن من 6 أرقام والمرسل إلى',
      codeLabel: 'رمز التحقق',
      codePlaceholder: '000000',
      verify: 'تحقق وسجّل الدخول',
      resend: 'إرسال رمز جديد',
      resendIn: 'إعادة الإرسال خلال {seconds} ث',
      useDifferent: 'استخدام بريد أو رقم آخر',
      recovery: 'لم يعد لديك وصول إلى وسائل الاتصال الموثّقة؟',
      recoveryLink: 'طلب استعادة الحساب',
      successTitle: 'تم تسجيل دخولك بأمان',
      successDescription: 'جلستك جاهزة، وسيقتصر الوصول على سجلات الأسرة والطلاب المصرّح لك بها.',
      enterPortal: 'المتابعة إلى الحساب',
    },
    register: {
      metadataTitle: 'إنشاء حساب',
      title: 'أنشئ حساب الأسرة',
      description: 'أدخل بيانات ولي الأمر والطالب والطلب التعليمي. سننشئ الملف ونضع التجربة المجانية في قائمة التعيين.',
      existing: 'لديك حساب بالفعل؟',
      existingLink: 'سجّل الدخول',
      steps: ['ولي الأمر', 'الطالب', 'الاحتياج التعليمي', 'المراجعة'],
      stepLabel: 'الخطوة {current} من {total}',
      guardianTitle: 'بيانات ولي الأمر',
      guardianDescription: 'استخدم وسائل اتصال يمكنك التحقق منها. يجب أن يمتلك كل ولي أمر هوية دخول مستقلة وآمنة.',
      parentName: 'الاسم الكامل لولي الأمر',
      relationship: 'صلة القرابة بالطالب',
      relationshipOptions: ['الأب أو الأم', 'ولي أمر', 'شخص بالغ مخوّل'],
      email: 'البريد الإلكتروني',
      whatsapp: 'رقم WhatsApp',
      telephone: 'رقم هاتف آخر',
      contactHint: 'أدخل رمز الدولة، مثال: +1 647 000 0000.',
      studentTitle: 'بيانات الطالب',
      studentDescription: 'سيتم ربط الطالب الجديد بالحساب فقط بعد التحقق من ولي الأمر.',
      studentName: 'الاسم الأول للطالب',
      grade: 'الصف الدراسي',
      gradePlaceholder: 'اختر الصف',
      learningTitle: 'احتياج الطالب وتفضيلات التجربة',
      learningDescription: 'تساعد التفضيلات فريقنا في اختيار المعلم المناسب، لكنها لا تحجز موعداً تلقائياً.',
      subject: 'المادة',
      curriculum: 'المنهج',
      language: 'لغة التدريس المفضلة',
      country: 'الدولة',
      timezone: 'المنطقة الزمنية',
      preferredDay: 'اليوم المفضل',
      preferredTime: 'الوقت المفضل',
      select: 'اختر من القائمة',
      reviewTitle: 'راجع بيانات التسجيل',
      reviewDescription: 'تأكد من البيانات قبل إنشاء الحساب وطلب التجربة المجانية المعلّق.',
      consent: 'أوافق على سياسة الخصوصية وأسمح لـSuccess Path Mentors باستخدام هذه البيانات لإنشاء الحساب والتواصل معي وترتيب الحصة التجريبية.',
      submit: 'إنشاء الحساب وطلب حصة تجريبية',
      noAutoBooking: 'تبقى التجربة بحالة WAITING_FOR_ASSIGNMENT حتى يؤكد موظف مخوّل اسم المعلم والموعد.',
      verifyTitle: 'تحقق من وسيلة الاتصال',
      verifyDescription: 'أدخل الرمز المكوّن من 6 أرقام والمرسل إلى',
      existingMatchTitle: 'تم العثور على حساب أسرة قائم',
      existingMatchDescription: 'تحقق من ملكية الحساب قبل إضافة الطالب. هكذا نمنع إنشاء حساب مكرر لولي الأمر.',
      reviewStatusTitle: 'تم استلام التسجيل للمراجعة الآمنة',
      reviewStatusDescription: 'وجدنا أكثر من تطابق محتمل، لذلك لم نفترض أي رابط. سيقوم الفريق بمراجعة الهوية بأمان.',
      successTitle: 'تم استلام التسجيل',
      successDescription: 'أصبح حسابك وملف الطالب جاهزين، والتجربة المجانية بانتظار تعيين المعلم والموعد.',
      successNext: 'سيرسل الفريق تأكيد المعلم وموعد التجربة عبر وسيلة الاتصال الموثّقة.',
      registrationId: 'رقم مرجع التسجيل',
      returnHome: 'العودة إلى الموقع',
      errors: {
        required: 'هذا الحقل مطلوب.',
        email: 'أدخل بريداً إلكترونياً صحيحاً.',
        phone: 'أدخل رقماً دولياً صحيحاً مع رمز الدولة.',
        consent: 'الموافقة مطلوبة لإنشاء الحساب.',
      },
    },
    social: {
      continueWithGoogle: 'المتابعة باستخدام Google',
      continueWithFacebook: 'المتابعة باستخدام Facebook',
      or: 'أو',
      connecting: 'جارٍ الاتصال…',
      unavailableError: 'تعذّر بدء تسجيل الدخول بهذه الطريقة حالياً. يمكنك المحاولة مجدداً أو استخدام البريد الإلكتروني أو الهاتف أدناه.',
      signupWithEmail: 'إنشاء حساب بالبريد الإلكتروني',
      signupWithWhatsapp: 'إنشاء حساب بواسطة واتساب',
      signupSubtitle: 'اختر طريقة التسجيل. يبدأ المسار بالتحقق من هويتك، ثم إكمال بيانات حسابك.',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
      changeMethod: 'تغيير طريقة التسجيل',
      adultNoticeTitle: 'تنبيه للعائلات والمتعلمين البالغين',
      adultNoticeDescription: 'تم تصميم التسجيل الإلكتروني لحسابات العائلات والطلاب. بالنسبة للمتعلمين البالغين، يمكنكم تنسيق البرنامج التعليمي مباشرة عبر واتساب مع فريق التنسيق.',
      adultNoticeAction: 'بدء طلب حصة تجريبية',
      emailInputTitle: 'إنشاء حساب بالبريد الإلكتروني',
      emailInputDescription: 'أدخل بريدك الإلكتروني. سنرسل رمز تحقق آمن قبل إكمال بيانات حسابك.',
      whatsappInputTitle: 'إنشاء حساب بواسطة واتساب',
      whatsappInputDescription: 'أدخل رقم هاتفك المسجل في واتساب مع رمز الدولة. سنرسل رمز تحقق آمن قبل إكمال بيانات حسابك.',
      sendVerificationCode: 'إرسال رمز التحقق',
      otpTitle: 'إدخال رمز التحقق',
      otpDescription: 'أدخل الرمز المكون من 6 أرقام والمُرسل إلى',
      verifyAndContinue: 'تأكيد الرمز والمتابعة',
      verifiedLabel: 'هوية مؤكدة',
      verifiedWithGoogle: 'تم التحقق بواسطة Google',
      verifiedWithFacebook: 'تم التحقق بواسطة Facebook',
      verifiedWithEmail: 'تم التحقق بالبريد الإلكتروني',
      verifiedWithWhatsapp: 'تم التحقق بواسطة واتساب',
    },
  },
  de: {
    common: {
      secure: 'Sicheres einheitliches Konto',
      backHome: 'Zurück zur Website',
      required: 'Erforderlich',
      optional: 'Optional',
      continue: 'Weiter',
      back: 'Zurück',
      loading: 'Bitte warten…',
      demo: 'Interaktiver Demomodus: Verwenden Sie einen beliebigen 6-stelligen Code. Dieser Hinweis verschwindet, sobald die Live-API aktiv ist.',
      privacy: 'Ihre geschäftlichen IDs werden niemals als Anmeldedaten verwendet.',
      apiError: 'Die Anfrage konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
      timeoutError: 'Die Anfrage hat zu lange gedauert. Bitte versuchen Sie es erneut.',
      networkError: 'Überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.',
      invalidOtp: 'Geben Sie den gültigen 6-stelligen Code ein, der an Sie gesendet wurde.',
      expiredOtp: 'Dieser Code ist abgelaufen. Fordern Sie einen neuen an.',
      rateLimited: 'Zu viele Versuche. Bitte warten Sie einen Moment, bevor Sie es erneut versuchen.',
    },
    shell: {
      eyebrow: 'Ein Konto. Jede Lernreise.',
      title: 'Ein sicheres Zuhause für das Lernen Ihrer Familie.',
      description: 'Greifen Sie auf alle autorisierten Schüler, Probestunden, Unterrichtsstunden und zukünftigen Dienste über eine verifizierte Identität zu.',
      points: [
        'Ein Konto für alle berechtigten Schüler',
        'Separater sicherer Zugang für jeden Erziehungsberechtigten',
        'Verifizierte Anmeldung per E-Mail, WhatsApp oder Mobiltelefon',
      ],
      family: 'Ihr Familienkonto',
      guardianA: 'Erziehungsberechtigter 1',
      guardianB: 'Erziehungsberechtigter 2',
      students: 'Berechtigte Schüler',
    },
    login: {
      metadataTitle: 'Eltern- & Schüler-Login',
      title: 'Willkommen zurück',
      description: 'Melden Sie sich mit einer verifizierten E-Mail-Adresse, WhatsApp-Nummer oder Mobilfunknummer an. Kein Passwort erforderlich.',
      identifierLabel: 'E-Mail, WhatsApp- oder Mobilfunknummer',
      identifierPlaceholder: 'name@beispiel.de oder +49 151 0000 0000',
      identifierHint: 'Geben Sie keine Parent MID oder Student MID ein.',
      requestCode: 'Sicherheitscode senden',
      createAccount: 'Neu bei Success Path Mentors?',
      createAccountLink: 'Familienkonto erstellen',
      staffPrompt: 'Lehrkraft oder Teammitglied?',
      staffLink: 'Mitarbeiter-Login nutzen',
      codeTitle: 'Überprüfen Sie Ihre Nachrichten',
      codeDescription: 'Geben Sie den 6-stelligen Code ein, gesendet an',
      codeLabel: 'Bestätigungscode',
      codePlaceholder: '000000',
      verify: 'Bestätigen und anmelden',
      resend: 'Neuen Code senden',
      resendIn: 'Erneut senden in {seconds}s',
      useDifferent: 'Andere E-Mail oder Nummer verwenden',
      recovery: 'Keinen Zugriff mehr auf Ihre verifizierten Kontakte?',
      recoveryLink: 'Kontowiederherstellung anfordern',
      successTitle: 'Erfolgreich angemeldet',
      successDescription: 'Ihre Sitzung ist bereit. Der Zugriff ist auf Ihre autorisierten Familien- und Schülerdaten beschränkt.',
      enterPortal: 'Weiter zu Ihrem Konto',
    },
    register: {
      metadataTitle: 'Konto erstellen',
      title: 'Familienkonto erstellen',
      description: 'Geben Sie Angaben zum Erziehungsberechtigten, Schüler und den Lernbedarf ein. Wir erstellen das Profil und reihen die kostenlose Probestunde in die Zuweisung ein.',
      existing: 'Bereits registriert?',
      existingLink: 'Stattdessen anmelden',
      steps: ['Erziehungsberechtigter', 'Schüler', 'Lernbedarf', 'Überprüfung'],
      stepLabel: 'Schritt {current} von {total}',
      guardianTitle: 'Angaben zum Erziehungsberechtigten',
      guardianDescription: 'Verwenden Sie Kontaktdaten, die Sie bestätigen können. Jeder Erziehungsberechtigte erhält eine individuelle Identität.',
      parentName: 'Vollständiger Name des Erziehungsberechtigten',
      relationship: 'Beziehung zum Schüler',
      relationshipOptions: ['Elternteil', 'Erziehungsberechtigter', 'Andere bevollmächtigte Person'],
      email: 'E-Mail-Adresse',
      whatsapp: 'WhatsApp-Nummer',
      telephone: 'Weitere Telefonnummer',
      contactHint: 'Inklusive Ländervorwahl, z. B. +49 151 0000 0000.',
      studentTitle: 'Angaben zum Schüler',
      studentDescription: 'Ein neues Schülerprofil wird erst nach Bestätigung des Erziehungsberechtigten verknüpft.',
      studentName: 'Vorname des Schülers',
      grade: 'Klassenstufe',
      gradePlaceholder: 'Klassenstufe auswählen',
      learningTitle: 'Lern- und Probestunden-Präferenzen',
      learningDescription: 'Präferenzen helfen unserem Team, die passende Lehrkraft auszuwählen. Sie buchen keinen Termin automatisch.',
      subject: 'Fach',
      curriculum: 'Lehrplan / Schulsystem',
      language: 'Bevorzugte Unterrichtssprache',
      country: 'Land',
      timezone: 'Zeitzone',
      preferredDay: 'Bevorzugter Wochentag',
      preferredTime: 'Bevorzugte Uhrzeit',
      select: 'Bitte auswählen',
      reviewTitle: 'Überprüfen Sie Ihre Angaben',
      reviewDescription: 'Bestätigen Sie die Details vor der Erstellung des Kontos und der Probestunden-Anfrage.',
      consent: 'Ich stimme der Datenschutzerklärung zu und ermächtige Success Path Mentors, diese Daten zur Kontoerstellung, Kontaktaufnahme und Organisation der Probestunde zu verwenden.',
      submit: 'Konto erstellen & Probestunde anfragen',
      noAutoBooking: 'Die Probestunde verbleibt im Status WAITING_FOR_ASSIGNMENT, bis ein Teammitglied Lehrkraft und Termin bestätigt.',
      verifyTitle: 'Kontakt bestätigen',
      verifyDescription: 'Geben Sie den 6-stelligen Code ein, gesendet an',
      existingMatchTitle: 'Bestehendes Familienkonto gefunden',
      existingMatchDescription: 'Bestätigen Sie die Inhaberschaft, bevor dieser Schüler hinzugefügt wird, um doppelte Konten zu vermeiden.',
      reviewStatusTitle: 'Registrierung zur sicheren Überprüfung erhalten',
      reviewStatusDescription: 'Wir haben mögliche Übereinstimmungen gefunden. Unser Team wird die Identität sicher prüfen.',
      successTitle: 'Registrierung eingegangen',
      successDescription: 'Ihr Konto und Schülerprofil sind bereit. Die Probestunde wartet auf Lehrkraft- und Terminzuweisung.',
      successNext: 'Unser Team bestätigt Lehrkraft und Termin über Ihre verifizierte Kontaktmethode.',
      registrationId: 'Registrierungs-Referenz',
      returnHome: 'Zurück zur Website',
      errors: {
        required: 'Dieses Feld ist erforderlich.',
        email: 'Geben Sie eine gültige E-Mail-Adresse ein.',
        phone: 'Geben Sie eine gültige internationale Nummer mit Ländervorwahl ein.',
        consent: 'Die Einwilligung ist zur Kontoerstellung erforderlich.',
      },
    },
    social: {
      continueWithGoogle: 'Mit Google fortfahren',
      continueWithFacebook: 'Mit Facebook fortfahren',
      or: 'ODER',
      connecting: 'Verbindung wird hergestellt…',
      unavailableError: 'Diese Anmeldemethode ist derzeit nicht verfügbar. Versuchen Sie es erneut oder nutzen Sie E-Mail oder Telefon unten.',
      signupWithEmail: 'Mit E-Mail registrieren',
      signupWithWhatsapp: 'Mit WhatsApp registrieren',
      signupSubtitle: 'Wählen Sie eine Registrierungsmethode. Bestätigen Sie zuerst Ihre Identität und vervollständigen Sie dann Ihre Kontodaten.',
      alreadyHaveAccount: 'Bereits ein Konto?',
      signIn: 'Anmelden',
      changeMethod: 'Registrierungsmethode ändern',
      adultNoticeTitle: 'Hinweis für Familien & erwachsene Lernende',
      adultNoticeDescription: 'Die Online-Kontoerstellung ist für Familien- und Schülerprofile ausgelegt. Erwachsene Einzellernende können ihr Programm direkt unverbindlich mit unserem Koordinationsteam per WhatsApp abstimmen.',
      adultNoticeAction: 'Kostenlose Probestunde / Anfrage starten',
      emailInputTitle: 'Mit E-Mail registrieren',
      emailInputDescription: 'Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Sicherheitscode, bevor Sie Ihre Kontodaten eingeben.',
      whatsappInputTitle: 'Mit WhatsApp registrieren',
      whatsappInputDescription: 'Geben Sie Ihre WhatsApp-Mobilfunknummer ein. Wir senden Ihnen einen Sicherheitscode, bevor Sie Ihre Kontodaten eingeben.',
      sendVerificationCode: 'Bestätigungscode senden',
      otpTitle: 'Bestätigungscode eingeben',
      otpDescription: 'Geben Sie den 6-stelligen Code ein, gesendet an',
      verifyAndContinue: 'Bestätigen & fortfahren',
      verifiedLabel: 'Bestätigte Identität',
      verifiedWithGoogle: 'Mit Google bestätigt',
      verifiedWithFacebook: 'Mit Facebook bestätigt',
      verifiedWithEmail: 'Mit E-Mail bestätigt',
      verifiedWithWhatsapp: 'Mit WhatsApp bestätigt',
    },
  },
} as const;

export function getAuthCopy(locale: AuthUiLocale) {
  return authCopy[locale];
}
