import type { AuthLocale } from './auth-contracts';

export const authCopy = {
  en: {
    common: {
      secure: 'Secure unified account',
      backHome: 'Back to website',
      required: 'Required',
      optional: 'Optional',
      continue: 'Continue',
      back: 'Back',
      loading: 'Please wait…',
      demo: 'Interactive demo mode: use any 6-digit code. This notice disappears when the live API is enabled.',
      privacy: 'Your business IDs are never used as login credentials.',
      apiError: 'We could not complete that request. Please try again.',
      timeoutError: 'The request took too long. Please try again.',
      networkError: 'Check your connection and try again.',
      invalidOtp: 'Enter the valid 6-digit code sent to you.',
      expiredOtp: 'This code has expired. Request a new one.',
      rateLimited: 'Too many attempts. Please wait before trying again.',
    },
    shell: {
      eyebrow: 'One account. Every learning journey.',
      title: 'A secure home for your family’s learning.',
      description: 'Access every authorized student, trial lesson, class and future service through one verified identity.',
      points: [
        'One account for all authorized students',
        'Separate secure access for every guardian',
        'Verified email, WhatsApp or mobile sign-in',
      ],
      family: 'Your family account',
      guardianA: 'Guardian 1',
      guardianB: 'Guardian 2',
      students: 'Authorized students',
    },
    login: {
      metadataTitle: 'Parent & Student Login',
      title: 'Welcome back',
      description: 'Sign in with a verified email, WhatsApp number or mobile number. No password is required.',
      identifierLabel: 'Email, WhatsApp or mobile number',
      identifierPlaceholder: 'name@example.com or +1 647 000 0000',
      identifierHint: 'Do not enter a Parent MID or Student MID.',
      requestCode: 'Send secure code',
      createAccount: 'New to Success Path Mentors?',
      createAccountLink: 'Create your family account',
      staffPrompt: 'Tutor or staff member?',
      staffLink: 'Use staff sign-in',
      codeTitle: 'Check your messages',
      codeDescription: 'Enter the 6-digit code sent to',
      codeLabel: 'Verification code',
      codePlaceholder: '000000',
      verify: 'Verify and sign in',
      resend: 'Send a new code',
      resendIn: 'Resend in {seconds}s',
      useDifferent: 'Use a different email or number',
      recovery: 'No longer have access to your verified contacts?',
      recoveryLink: 'Request account recovery',
      successTitle: 'You are securely signed in',
      successDescription: 'Your session is ready. Access is limited to your authorized family and student records.',
      enterPortal: 'Continue to your account',
    },
    register: {
      metadataTitle: 'Create an Account',
      title: 'Create your family account',
      description: 'Tell us about the guardian, student and learning request. We will create the profile and place the free trial in the assignment queue.',
      existing: 'Already registered?',
      existingLink: 'Sign in instead',
      steps: ['Guardian', 'Student', 'Learning needs', 'Review'],
      stepLabel: 'Step {current} of {total}',
      guardianTitle: 'Guardian information',
      guardianDescription: 'Use contacts you can verify. Each guardian should have an individual secure identity.',
      parentName: 'Parent or guardian full name',
      relationship: 'Relationship to student',
      relationshipOptions: ['Parent', 'Guardian', 'Other authorized adult'],
      email: 'Email address',
      whatsapp: 'WhatsApp number',
      telephone: 'Other mobile number',
      contactHint: 'Include the country code, for example +1 647 000 0000.',
      studentTitle: 'Student information',
      studentDescription: 'A new student record will be linked only after guardian verification.',
      studentName: 'Student first name',
      grade: 'Grade',
      gradePlaceholder: 'Select grade',
      learningTitle: 'Learning and trial preferences',
      learningDescription: 'Preferences help our team assign the right teacher. They do not automatically book a slot.',
      subject: 'Subject',
      curriculum: 'Curriculum',
      language: 'Preferred teaching language',
      country: 'Country',
      timezone: 'Time zone',
      preferredDay: 'Preferred day',
      preferredTime: 'Preferred time',
      select: 'Select an option',
      reviewTitle: 'Review your registration',
      reviewDescription: 'Confirm the details before creating the account and pending free-trial request.',
      consent: 'I agree to the Privacy Policy and authorize Success Path Mentors to use these details to create the account, contact me and arrange the trial.',
      submit: 'Create account & request free trial',
      noAutoBooking: 'The trial remains WAITING_FOR_ASSIGNMENT until an authorized team member confirms the teacher and time.',
      verifyTitle: 'Verify your contact',
      verifyDescription: 'Enter the 6-digit code sent to',
      existingMatchTitle: 'Existing family account found',
      existingMatchDescription: 'Verify ownership before we add this student. This prevents duplicate parent accounts.',
      reviewStatusTitle: 'Registration received for secure review',
      reviewStatusDescription: 'We found conflicting possible matches, so no account link was guessed. Our team will review the identity safely.',
      successTitle: 'Registration received',
      successDescription: 'Your account and student profile are ready. The free trial is waiting for teacher and time assignment.',
      successNext: 'Our team will confirm the free-trial teacher and time by your verified contact method.',
      registrationId: 'Registration reference',
      returnHome: 'Return to website',
      errors: {
        required: 'This field is required.',
        email: 'Enter a valid email address.',
        phone: 'Enter a valid international number with country code.',
        consent: 'Consent is required to create the account.',
      },
    },
  },
  ar: {
    common: {
      secure: 'حساب موحّد وآمن',
      backHome: 'العودة إلى الموقع',
      required: 'مطلوب',
      optional: 'اختياري',
      continue: 'متابعة',
      back: 'رجوع',
      loading: 'يرجى الانتظار…',
      demo: 'وضع العرض التفاعلي: أدخل أي رمز مكوّن من 6 أرقام. تختفي هذه الملاحظة عند تفعيل الـAPI الفعلي.',
      privacy: 'لا تُستخدم أرقام Parent MID أو Student MID لتسجيل الدخول أبداً.',
      apiError: 'تعذر إكمال الطلب. يرجى المحاولة مرة أخرى.',
      timeoutError: 'استغرق الطلب وقتاً طويلاً. يرجى المحاولة مرة أخرى.',
      networkError: 'تحقق من اتصال الإنترنت ثم حاول مرة أخرى.',
      invalidOtp: 'أدخل رمز التحقق الصحيح المكوّن من 6 أرقام.',
      expiredOtp: 'انتهت صلاحية الرمز. اطلب رمزاً جديداً.',
      rateLimited: 'تم تجاوز عدد المحاولات. يرجى الانتظار قبل المحاولة مجدداً.',
    },
    shell: {
      eyebrow: 'حساب واحد لكل رحلة تعليمية',
      title: 'مساحة آمنة لتعلّم جميع أفراد الأسرة.',
      description: 'ادخل إلى ملفات الطلاب المصرّح لك بها والحصص والتجربة المجانية والخدمات المستقبلية من خلال هوية واحدة موثّقة.',
      points: [
        'حساب واحد لجميع الطلاب المصرّح بهم',
        'دخول مستقل وآمن لكل ولي أمر',
        'التحقق عبر البريد أو WhatsApp أو الهاتف',
      ],
      family: 'حساب الأسرة',
      guardianA: 'ولي الأمر الأول',
      guardianB: 'ولي الأمر الثاني',
      students: 'الطلاب المصرّح بهم',
    },
    login: {
      metadataTitle: 'دخول ولي الأمر والطالب',
      title: 'مرحباً بعودتك',
      description: 'سجّل الدخول باستخدام بريد إلكتروني أو رقم WhatsApp أو هاتف موثّق. لا تحتاج إلى كلمة مرور.',
      identifierLabel: 'البريد أو رقم WhatsApp أو الهاتف',
      identifierPlaceholder: 'name@example.com أو +1 647 000 0000',
      identifierHint: 'لا تدخل Parent MID أو Student MID.',
      requestCode: 'إرسال رمز آمن',
      createAccount: 'جديد لدى Success Path Mentors؟',
      createAccountLink: 'أنشئ حساب الأسرة',
      staffPrompt: 'هل أنت معلماً أو من فريق العمل؟',
      staffLink: 'استخدم دخول الموظفين',
      codeTitle: 'تحقق من رسائلك',
      codeDescription: 'أدخل الرمز المكوّن من 6 أرقام والمرسل إلى',
      codeLabel: 'رمز التحقق',
      codePlaceholder: '000000',
      verify: 'تحقق وسجّل الدخول',
      resend: 'إرسال رمز جديد',
      resendIn: 'إعادة الإرسال خلال {seconds} ث',
      useDifferent: 'استخدام بريد أو رقم آخر',
      recovery: 'لم يعد لديك وصول إلى وسائل الاتصال الموثّقة؟',
      recoveryLink: 'طلب استعادة الحساب',
      successTitle: 'تم تسجيل دخولك بأمان',
      successDescription: 'جلستك جاهزة، وسيقتصر الوصول على سجلات الأسرة والطلاب المصرّح لك بها.',
      enterPortal: 'المتابعة إلى الحساب',
    },
    register: {
      metadataTitle: 'إنشاء حساب',
      title: 'أنشئ حساب الأسرة',
      description: 'أدخل بيانات ولي الأمر والطالب والطلب التعليمي. سننشئ الملف ونضع التجربة المجانية في قائمة التعيين.',
      existing: 'لديك حساب بالفعل؟',
      existingLink: 'سجّل الدخول',
      steps: ['ولي الأمر', 'الطالب', 'الاحتياج التعليمي', 'المراجعة'],
      stepLabel: 'الخطوة {current} من {total}',
      guardianTitle: 'بيانات ولي الأمر',
      guardianDescription: 'استخدم وسائل اتصال يمكنك التحقق منها. يجب أن يمتلك كل ولي أمر هوية دخول مستقلة وآمنة.',
      parentName: 'الاسم الكامل لولي الأمر',
      relationship: 'صلة القرابة بالطالب',
      relationshipOptions: ['الأب أو الأم', 'ولي أمر', 'شخص بالغ مخوّل'],
      email: 'البريد الإلكتروني',
      whatsapp: 'رقم WhatsApp',
      telephone: 'رقم هاتف آخر',
      contactHint: 'أدخل رمز الدولة، مثال: +1 647 000 0000.',
      studentTitle: 'بيانات الطالب',
      studentDescription: 'سيتم ربط الطالب الجديد بالحساب فقط بعد التحقق من ولي الأمر.',
      studentName: 'الاسم الأول للطالب',
      grade: 'الصف الدراسي',
      gradePlaceholder: 'اختر الصف',
      learningTitle: 'احتياج الطالب وتفضيلات التجربة',
      learningDescription: 'تساعد التفضيلات فريقنا في اختيار المعلم المناسب، لكنها لا تحجز موعداً تلقائياً.',
      subject: 'المادة',
      curriculum: 'المنهج',
      language: 'لغة التدريس المفضلة',
      country: 'الدولة',
      timezone: 'المنطقة الزمنية',
      preferredDay: 'اليوم المفضل',
      preferredTime: 'الوقت المفضل',
      select: 'اختر من القائمة',
      reviewTitle: 'راجع بيانات التسجيل',
      reviewDescription: 'تأكد من البيانات قبل إنشاء الحساب وطلب التجربة المجانية المعلّق.',
      consent: 'أوافق على سياسة الخصوصية وأسمح لـSuccess Path Mentors باستخدام هذه البيانات لإنشاء الحساب والتواصل معي وترتيب الحصة التجريبية.',
      submit: 'إنشاء الحساب وطلب حصة تجريبية',
      noAutoBooking: 'تبقى التجربة بحالة WAITING_FOR_ASSIGNMENT حتى يؤكد موظف مخوّل اسم المعلم والموعد.',
      verifyTitle: 'تحقق من وسيلة الاتصال',
      verifyDescription: 'أدخل الرمز المكوّن من 6 أرقام والمرسل إلى',
      existingMatchTitle: 'تم العثور على حساب أسرة قائم',
      existingMatchDescription: 'تحقق من ملكية الحساب قبل إضافة الطالب. هكذا نمنع إنشاء حساب مكرر لولي الأمر.',
      reviewStatusTitle: 'تم استلام التسجيل للمراجعة الآمنة',
      reviewStatusDescription: 'وجدنا أكثر من تطابق محتمل، لذلك لم نفترض أي رابط. سيقوم الفريق بمراجعة الهوية بأمان.',
      successTitle: 'تم استلام التسجيل',
      successDescription: 'أصبح حسابك وملف الطالب جاهزين، والتجربة المجانية بانتظار تعيين المعلم والموعد.',
      successNext: 'سيرسل الفريق تأكيد المعلم وموعد التجربة عبر وسيلة الاتصال الموثّقة.',
      registrationId: 'رقم مرجع التسجيل',
      returnHome: 'العودة إلى الموقع',
      errors: {
        required: 'هذا الحقل مطلوب.',
        email: 'أدخل بريداً إلكترونياً صحيحاً.',
        phone: 'أدخل رقماً دولياً صحيحاً مع رمز الدولة.',
        consent: 'الموافقة مطلوبة لإنشاء الحساب.',
      },
    },
  },
} as const;

export function getAuthCopy(locale: AuthLocale) {
  return authCopy[locale];
}
