import fs from 'node:fs';
const base=process.argv[2]||'https://successpathmentors.net';
const label=process.argv[3]||'live';
const official='https://successpathmentors.net';
const decode=s=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const attrs=s=>Object.fromEntries([...s.matchAll(/([\w:-]+)\s*=\s*["']([^"']*)["']/g)].map(m=>[m[1].toLowerCase(),decode(m[2])]));
const request=async path=>{try{const r=await fetch(base+path,{signal:AbortSignal.timeout(25000)});return {status:r.status,final:new URL(r.url).pathname,html:await r.text()}}catch(e){return{status:0,final:path,html:'',error:String(e)}}};
const sitemap=await request('/sitemap.xml');
const paths=new Set(['/en','/ar','/fr','/en/about','/en/how-it-works','/en/locations/canada',...JSON.parse(fs.readFileSync('reports/seo/location-paths.json','utf8'))]);
for(const m of sitemap.html.matchAll(/(?:<loc>|href=")(https:\/\/successpathmentors.net[^<"]*)/g))paths.add(new URL(decode(m[1])).pathname);
const queue=[...paths], rows=[], links=new Set();let completed=0;
async function worker(){while(queue.length){const path=queue.shift(),r=await request(path),h=r.html;const meta=Object.fromEntries([...h.matchAll(/<meta\b[^>]*>/g)].map(m=>{const a=attrs(m[0]);return [a.name||a.property,a.content]}));const linkTags=[...h.matchAll(/<link\b[^>]*>/g)].map(m=>attrs(m[0]));const canonical=linkTags.find(a=>a.rel==='canonical')?.href;const alternates=linkTags.filter(a=>a.rel==='alternate'&&a.hreflang);for(const target of [canonical,...alternates.map(a=>a.href)]) if(target) {const u=new URL(target);if(u.origin===official&&!paths.has(u.pathname)){paths.add(u.pathname);queue.push(u.pathname)}} const schemas=[];let invalid=0;for(const m of h.matchAll(/<script\b[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g))try{schemas.push(JSON.parse(m[1]))}catch{invalid++}const body=h.replace(/<script\b[\s\S]*?<\/script>/g,'').replace(/<style\b[\s\S]*?<\/style>/g,'');for(const m of body.matchAll(/<a\b[^>]*>/g)){const a=attrs(m[0]);if(a.href)try{const u=new URL(a.href,official+path);if(u.origin===official)links.add(u.pathname)}catch{}}
const title=decode(h.match(/<title>([\s\S]*?)<\/title>/)?.[1]||'');const legacy=/mustafa[ -]?academy|أكاديمية مصطفى|مصطفى أكاديمي|سكسس باث منتورز/i.test(body+JSON.stringify(meta)+JSON.stringify(schemas));const trust=/2,000|700\+|\+700|100% secure/.test(body);rows.push({path,status:r.status,final:r.final,error:r.error,title,description:meta.description,canonical,canonicalCorrect:canonical===official+r.final,alternates,ogTitle:meta['og:title'],ogDescription:meta['og:description'],twitterTitle:meta['twitter:title'],twitterDescription:meta['twitter:description'],lang:attrs(h.match(/<html\b[^>]*>/)?.[0]||'').lang,h1Count:(body.match(/<h1\b/g)||[]).length,legacy,unverifiedNumericClaims:trust,schemaCount:schemas.length,invalidJsonLd:invalid,schemas});completed++;if(completed%100===0)console.log(label,completed,'/',paths.size)}}
await Promise.all(Array.from({length:base.includes('localhost')?8:4},worker));
const checks=[];const additional=[...links].filter(p=>!paths.has(p));let cursor=0;await Promise.all(Array.from({length:4},async()=>{while(cursor<additional.length){const path=additional[cursor++];const r=await request(path);checks.push({path,status:r.status,final:r.final,error:r.error})}}));
for(const row of rows){const target=rows.find(r=>official+r.final===row.canonical);row.canonicalCorrect=Boolean(target&&target.status===200&&target.canonical===row.canonical)}
const summary={timestamp:new Date().toISOString(),base,pages:rows.length,failed:rows.filter(r=>r.status!==200).map(r=>({path:r.path,status:r.status,error:r.error})),legacy:rows.filter(r=>r.legacy).length,unverifiedNumericClaims:rows.filter(r=>r.unverifiedNumericClaims).length,metadataIssues:rows.filter(r=>!r.title||!r.description||!r.canonicalCorrect||!r.ogTitle||!r.ogDescription||!r.twitterTitle||!r.twitterDescription).map(r=>r.path),invalidJsonLd:rows.filter(r=>r.invalidJsonLd).length,brokenLinks:[...checks,...rows].filter(r=>r.status!==200),redirects:rows.filter(r=>r.final!==r.path).map(r=>({path:r.path,final:r.final}))};
fs.writeFileSync(`reports/seo/${label}-crawl.json`,JSON.stringify({summary,rows,additionalLinkChecks:checks},null,2));console.log(JSON.stringify({...summary,failed:summary.failed.length,metadataIssues:summary.metadataIssues.length,brokenLinks:summary.brokenLinks.length},null,2));
